theme:
  colors:
    primary:
      main: '#32329f'

# add description.md to opening page 
redocURL: https://redocpro-cdn.redoc.ly/v1.0.0-beta.13/redocpro-standalone.min.js
redocExport: RedocPro
unstable_externalDescription: description.md
